# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"YoloTarget": "00_fastai.ipynb"}

modules = ["data_block.py"]

doc_url = "https://red0orange.github.io/trash/"

git_url = "https://github.com/red0orange/trash/tree/master/"

def custom_doc_links(name): return None
