# AUTOGENERATED! DO NOT EDIT! File to edit: 00_fastai.ipynb (unless otherwise specified).

__all__ = ['YoloTarget']

# Cell
class YoloTarget(ImageBBox):
    """my custom yolo ItemBase"""
    def apply_tfms(self, tfms, **kwargs):
        return super(YoloTarget, self).apply_tfms(tfms, **kwargs)